name : Upload website to s3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::820137170977:role/iam_role_for_Github_Actions
          role-session-name: GithubActionSession
          aws-region: us-west-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://resume.louiecervantes.com/